// Package nftverify compares the nftables ruleset actually loaded in the kernel
// against what site.yaml describes.
//
// The ruleset is generated by deploy/pi/generate-nftables.py and only ever
// rewritten by install.sh. Editing site.yaml and restarting combiner therefore
// updates the reflector (which reads the YAML at startup) while leaving the
// firewall and NAT rules stale — a split brain in which -check happily reports
// "config OK" while the kernel SNATs to an address that no longer exists on the
// box. Every Control->Dante reply is then addressed to a dead host and the flows
// sit UNREPLIED.
//
// These checks are deliberately semantic rather than a textual diff: the goal is
// to catch a ruleset that contradicts site.yaml, not to demand byte equality
// with a freshly generated file (nft normalises its own output, e.g. rendering
// "snat to" as "snat ip to").
package nftverify

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/msnow/vunet-dante-combiner-2000/internal/config"
	"github.com/msnow/vunet-dante-combiner-2000/internal/nftexec"
)

// Result reports the outcome of a drift check.
type Result struct {
	// Skipped is set when the check could not run (nft missing, no table
	// loaded, insufficient privileges). A skip is not a failure: -check also
	// runs on laptops.
	Skipped string
	// Problems are concrete contradictions between the ruleset and site.yaml.
	Problems []string
	// Checked names the invariants that were confirmed.
	Checked []string
}

// OK reports whether the ruleset agrees with the config (or could not be read).
func (r Result) OK() bool { return len(r.Problems) == 0 }

var (
	// nft renders the loaded rule as "snat ip to 10.201.0.1"; the generated
	// file writes "snat to 10.201.0.1". Accept both.
	snatRe = regexp.MustCompile(`counter name "?(snat_to_\w+)"?\s+snat(?:\s+ip)?\s+to\s+([0-9.]+)`)
	// A missing table is reported by nft on stderr; treat it as "not loaded".
	noTableRe = regexp.MustCompile(`(?i)No such file or directory|does not exist`)
)

// Verify reads the loaded ruleset and compares it against site.
func Verify(site *config.Site) Result {
	if !nftexec.Available() {
		return Result{Skipped: "nft not installed"}
	}
	cmd, err := nftexec.Command("list", "table", "inet", "combiner")
	if err != nil {
		return Result{Skipped: err.Error()}
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		text := strings.TrimSpace(string(out))
		if noTableRe.MatchString(text) {
			return Result{Skipped: "no 'inet combiner' table loaded (run install.sh)"}
		}
		if text == "" {
			text = err.Error()
		}
		return Result{Skipped: fmt.Sprintf("could not read ruleset (%s)", firstLine(text))}
	}
	return compare(string(out), site)
}

// compare is the pure half of Verify, kept separate so it can be tested against
// captured nft output without a kernel.
func compare(ruleset string, site *config.Site) Result {
	var r Result

	// The SNAT source address is the invariant that silently breaks every
	// Control->Dante conversation when it goes stale, so check it first.
	want := map[string]string{"snat_to_dante": site.VLANs.Dante.Address}
	if site.HasMgmt() {
		want["snat_to_control"] = site.VLANs.Control.Address
	}

	found := map[string]string{}
	for _, m := range snatRe.FindAllStringSubmatch(ruleset, -1) {
		found[m[1]] = m[2]
	}

	for name, wantAddr := range want {
		got, ok := found[name]
		switch {
		case !ok:
			r.Problems = append(r.Problems, fmt.Sprintf(
				"%s rule missing from loaded ruleset (site.yaml expects SNAT to %s)", name, wantAddr))
		case got != wantAddr:
			r.Problems = append(r.Problems, fmt.Sprintf(
				"%s targets %s but site.yaml says %s — ruleset is stale; regenerate and reload", name, got, wantAddr))
		default:
			r.Checked = append(r.Checked, fmt.Sprintf("%s -> %s", name, got))
		}
	}
	// A SNAT rule the config does not call for means the ruleset was built from
	// a different profile (e.g. a Mgmt-enabled lab config).
	for name, got := range found {
		if _, expected := want[name]; !expected {
			r.Problems = append(r.Problems, fmt.Sprintf(
				"unexpected %s rule (SNAT to %s) — ruleset was built from a different site.yaml", name, got))
		}
	}

	// Interface names are the other half of the generated ruleset that tracks
	// site.yaml: a VLAN retag leaves rules pointing at a device that no longer
	// carries the traffic.
	phys := site.PhysicalInterface
	for role, v := range map[string]config.VLAN{
		"control": site.VLANs.Control,
		"dante":   site.VLANs.Dante,
	} {
		name := v.Iface(phys)
		if !strings.Contains(ruleset, `"`+name+`"`) {
			r.Problems = append(r.Problems, fmt.Sprintf(
				"no rule references %s interface %q — ruleset predates the current VLAN layout", role, name))
			continue
		}
		r.Checked = append(r.Checked, fmt.Sprintf("%s iface %s", role, name))
	}

	return r
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
