#!/usr/bin/env python3
"""Generate nftables.conf from combiner site.yaml.

Safety invariants:
- forward policy drop; only unicast Mgmt↔Control and Mgmt↔Dante
- all multicast forwarding dropped (reflector is the sole cross-VLAN mcast path)
- PTP/media drops apply toward Mgmt/Control from any source
- Control↔Dante never allowed
- IPv6 forwarding dropped
"""

from __future__ import annotations

import argparse
import ipaddress
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("PyYAML required: pip install pyyaml / apt install python3-yaml", file=sys.stderr)
    sys.exit(1)

IFACE_RE = re.compile(r"^[A-Za-z0-9._-]{1,15}$")

# Non-overridable floor — always denied toward Mgmt/Control (unioned with site.yaml).
FLOOR_DENY_PREFIXES = [
    "224.0.1.128/30",  # PTP 224.0.1.128-131 (covers 129-131)
    "224.0.1.132/32",  # PTP 224.0.1.132
    "239.255.0.0/16",  # Dante ATP media
    "239.69.0.0/16",  # AES67 media
    "239.254.3.3/32",  # PTP logging
]


def load_site(path: Path) -> dict[str, Any]:
    with path.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise SystemExit(f"site config must be a mapping: {path}")
    return data


def iface(vlan: dict[str, Any], phys: str) -> str:
    if vlan.get("untagged"):
        name = vlan.get("interface_name") or phys
        if name != phys:
            raise SystemExit(f"untagged interface_name must equal physical_interface {phys!r}, got {name!r}")
    else:
        name = vlan.get("interface_name") or f"{phys}.{vlan['id']}"
    if not IFACE_RE.match(name):
        raise SystemExit(f"invalid interface_name {name!r}")
    return name


def normalize_prefix(p: str) -> str:
    net = ipaddress.ip_network(p, strict=False)
    if not isinstance(net, ipaddress.IPv4Network):
        raise SystemExit(f"deny prefix must be IPv4: {p}")
    return str(net)


def merge_deny_prefixes(site: dict[str, Any]) -> list[str]:
    raw = list(FLOOR_DENY_PREFIXES)
    raw.extend(site.get("deny_multicast_prefixes") or [])
    seen: set[str] = set()
    out: list[str] = []
    for p in raw:
        n = normalize_prefix(p)
        if n not in seen:
            seen.add(n)
            out.append(n)
    return out


def validate_ipv4(addr: str, label: str) -> None:
    ip = ipaddress.ip_address(addr)
    if not isinstance(ip, ipaddress.IPv4Address):
        raise SystemExit(f"{label} must be IPv4: {addr}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("site_yaml")
    ap.add_argument("output", nargs="?", default="-")
    ap.add_argument(
        "--check",
        action="store_true",
        help="after write, run nft -c -f on the output (requires nft)",
    )
    args = ap.parse_args()

    site = load_site(Path(args.site_yaml))
    phys = site["physical_interface"]
    vlans = site["vlans"]
    mgmt = vlans["mgmt"]
    control = vlans["control"]
    dante = vlans["dante"]

    for label, v in (("mgmt", mgmt), ("control", control), ("dante", dante)):
        validate_ipv4(v["address"], f"{label}.address")
        if v.get("untagged") and label != "mgmt":
            raise SystemExit(f"{label}: untagged is only allowed on mgmt")

    i_mgmt = iface(mgmt, phys)
    i_control = iface(control, phys)
    i_dante = iface(dante, phys)

    if len({i_mgmt, i_control, i_dante}) != 3:
        raise SystemExit("mgmt/control/dante interface names must be distinct")
    if len({mgmt["id"], control["id"], dante["id"]}) != 3:
        raise SystemExit("mgmt/control/dante VLAN IDs must be distinct")

    deny_prefixes = merge_deny_prefixes(site)
    all_if = f'{{ "{i_mgmt}", "{i_control}", "{i_dante}" }}'
    mgmt_ctrl = f'{{ "{i_mgmt}", "{i_control}" }}'

    forward_denies = "\n".join(
        f'    oifname {mgmt_ctrl} ip daddr {p} counter name drop_deny_mcast drop comment "deny mcast {p}"'
        for p in deny_prefixes
    )
    input_denies = "\n".join(f'    iifname {all_if} ip daddr {p} drop comment "input deny {p}"' for p in deny_prefixes)

    text = f"""#!/usr/sbin/nft -f
# Generated by generate-nftables.py from {args.site_yaml}
# Do not edit by hand — regenerate from site.yaml
#
# Note: flush ruleset clears ALL tables on this host. Combiner Pi is dedicated.

flush ruleset

table inet combiner {{
  counter drop_ptp {{}}
  counter drop_deny_mcast {{}}
  counter drop_forward_mcast {{}}
  counter drop_control_dante {{}}
  counter drop_invalid_path {{}}
  counter drop_ipv6_forward {{}}
  counter snat_to_control {{}}
  counter snat_to_dante {{}}

  chain forward {{
    type filter hook forward priority filter; policy drop;

    ct state invalid drop

    # Hard isolation first (above established) so a prior fail-open window cannot stick
    iifname "{i_control}" oifname "{i_dante}" counter name drop_control_dante drop
    iifname "{i_dante}" oifname "{i_control}" counter name drop_control_dante drop

    # No IPv6 cross-VLAN forwarding
    meta nfproto ipv6 counter name drop_ipv6_forward drop

    # PTP (exact range) toward Mgmt or Control from any source
    oifname {mgmt_ctrl} ip daddr 224.0.1.129-224.0.1.132 udp dport {{ 319, 320 }} counter name drop_ptp drop

    # Floor + site deny prefixes toward Mgmt/Control
{forward_denies}

    # Reflector is the ONLY multicast cross-VLAN path — never kernel-forward mcast
    ip daddr 224.0.0.0/4 counter name drop_forward_mcast drop
    ip daddr 255.255.255.255 counter name drop_forward_mcast drop

    ct state established,related accept

    # Unicast only: Mgmt <-> Control
    iifname "{i_mgmt}" oifname "{i_control}" ip daddr != 224.0.0.0/4 accept
    iifname "{i_control}" oifname "{i_mgmt}" ip daddr != 224.0.0.0/4 accept

    # Unicast only: Mgmt <-> Dante
    iifname "{i_mgmt}" oifname "{i_dante}" ip daddr != 224.0.0.0/4 accept
    iifname "{i_dante}" oifname "{i_mgmt}" ip daddr != 224.0.0.0/4 accept

    counter name drop_invalid_path drop
  }}

  chain postrouting {{
    type nat hook postrouting priority srcnat; policy accept;

    oifname "{i_control}" ip saddr != {control["address"]} counter name snat_to_control snat to {control["address"]}
    oifname "{i_dante}" ip saddr != {dante["address"]} counter name snat_to_dante snat to {dante["address"]}
  }}

  chain input {{
    type filter hook input priority filter; policy drop;

    ct state invalid drop
    iif lo accept

    # Drop PTP/media to the box before any multicast accept
    iifname {all_if} ip daddr 224.0.1.129-224.0.1.132 udp dport {{ 319, 320 }} counter name drop_ptp drop
{input_denies}

    ct state established,related accept

    # Mgmt services: DHCP, status HTTP, SSH, ICMP (no DNS — clients get no DNS option)
    iifname "{i_mgmt}" udp dport {{ 67, 68 }} accept
    iifname "{i_mgmt}" tcp dport {{ 22, 8080 }} accept
    iifname "{i_mgmt}" icmp type echo-request accept

    # IGMP + UDP multicast for the reflector (after denies)
    meta l4proto igmp accept
    iifname {all_if} ip daddr 224.0.0.0/4 meta l4proto udp accept
    iifname {all_if} icmp type echo-request accept
  }}

  chain output {{
    type filter hook output priority filter; policy accept;
  }}
}}
"""

    if args.output == "-":
        sys.stdout.write(text)
    else:
        out = Path(args.output)
        out.write_text(text)
        print(f"Wrote {args.output}", file=sys.stderr)
        if args.check:
            r = subprocess.run(["nft", "-c", "-f", str(out)], capture_output=True, text=True)
            if r.returncode != 0:
                print(r.stderr or r.stdout, file=sys.stderr)
                return 1
            print("nft -c OK", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
